services:
  db:
    image: postgres:16-alpine
    container_name: backend_db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    profiles:
      - all
      - skezia
      - skemeet
      - auth
      - api

volumes:
  db_data:
